#!/bin/sh
eval `scramv1 runtime -sh`

echo "initializeSiStripDQM"
#./initializeSiStripDQM playback
echo " Start Application "
./start &
sleep 30
echo "Started the application and Configuring"
./configure
sleep 60
echo "Configured..."
./enable
echo "Enabled ..."


