def csclayout(i, p, *rows): i["CSC/Layouts/" + p] = DQMItem(layout=rows)

csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 01",
  	[{'path': "CSC/Summary/Physics_EMU", 'description': "CSC Efficiency for Physics. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#reportSummaryMap\">here</a>."}])
	
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 02",
  	[{'path': "CSC/Summary/Physics_ME1", 'description': "EMU station ME1 status: physics efficiency by reporting area and hardware efficiency based on reporting number of hardware elements. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#Summary_ME\">here</a>."},
  	 {'path': "CSC/Summary/Physics_ME2", 'description': "EMU station ME2 status: physics efficiency by reporting area and hardware efficiency based on reporting number of hardware elements. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#Summary_ME\">here</a>."}],
  	[{'path': "CSC/Summary/Physics_ME3", 'description': "EMU station ME3 status: physics efficiency by reporting area and hardware efficiency based on reporting number of hardware elements. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#Summary_ME\">here</a>."},
  	 {'path': "CSC/Summary/Physics_ME4", 'description': "EMU station ME4 status: physics efficiency by reporting area and hardware efficiency based on reporting number of hardware elements. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#Summary_ME\">here</a>."}])
	 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 03 - DDUs in Readout",
  	[{'path': "CSC/Summary/All_DDUs_in_Readout", 'description': "Number of Events in DDU. If Readout and Trigger Enable were started in a correct sequence (first, Readout Enable and, then, Trigger Enable) and the rate of events with CSC payload present is not too high (<100 CSCs with data per second per DDU) then all DDUs should give the exact same number of events. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#All_DDUs_in_Readout\">here</a>."}],
	[{'path': "CSC/Summary/All_DDUs_L1A_Increment", 'description': "L1A increment from event for each DDU. If Readout and Trigger Enable were started in a correct sequence (first, Readout Enable and, then, Trigger Enable) and the rate of events with CSC payload present is not too high (<100 CSCs with data per second per DDU) L1A increment from event to event must be 1. However, when the rate goes up, DAQ-DQM may not be able to keep up with the data and are designed to skip events. Occasional skips (L1A>1) will inevitably happen at low rates due to Poisson nature of cosmic ray rates. Under no circumstances, the incremental L1A can be zero. There should be no entries in the bottom row of bins of the bottom histogram. One may also want to flag runs with extremely non-uniform response DDUs. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#All_DDUs_L1A_Increment\">here</a>."}])	
	 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 04 - CSCs Reporting Data and Unpacked",
  	[{'path': "CSC/Summary/CSC_Reporting", 'description': "The occupancy histogram shows CSCs reporting data, regardless of whether data format was intact or broken. Chambers within one raw belong to one 360 - ring of chamber. Note that ME +/- 2/1, 3/1, and 4/1 rings have only 18 20 -chambers, while all others have 36 10 -chambers. The rainbow pattern of color within one row is due to directionality of cosmic rays. At LHC, all chambers within one row should have equal occupancy. One should check that there are no new empty cells (check for the list of currently disabled CSCs) there are no hot CSCs. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Reporting\">here</a>."}],
	[{'path': "CSC/Summary/CSC_Unpacked_Fract", 'description': "Histogram shows unpacking efficiency. Gross problems at a scale of >10% inefficiency can be easily seen as deviations from the flat red color corresponding to 100% efficiency. Smaller scale problems can be chased using the EMU Test10 canvas. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Unpacked_Fract\">here</a>."}])	 
	
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 05 - CSCs with Errors and Warnings (Fractions)",
  	[{'path': "CSC/Summary/CSC_Format_Errors_Fract", 'description': "Histogram shows frequency of format errors per CSC record. Pay attention to the temperature scale (it changes from run to run and during a run according to the histogram content). CSCs reporting format errors in more than 1% of events should be flagged. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Format_Errors_Fract\">here</a>."},
	 {'path': "CSC/Summary/CSC_L1A_out_of_sync_Fract", 'description': "(no description). For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_L1A_out_of_sync\">here</a>."}],
	[{'path': "CSC/Summary/CSC_DMB_input_fifo_full_Fract", 'description': "Shows a frequency of FIFO-FULL condition on DMB inputs (OR of 7 FIFOs: 5 CFEBs, ALCT, TMB). Appearance of entries in this histogram is very bad and would typically imply a loss of synchronization, even if FIFO-FULL condition clears away. To dig out which of the 7 boards is actually responsible for the trouble, one needs to refer the FEB Status (Timeouts, FIFO, L1 pipe) canvas for the offensive chamber (this canvas can be found in the DMB group) For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_DMB_input_fifo_full_Fract\">here</a>."},
	 {'path': "CSC/Summary/CSC_DMB_input_timeout_Fract", 'description': "Shows a frequency of a TIMEOUT condition on DMB inputs (OR start/stop timeouts for 5 CFEBs, ALCT, TMB). Appearance of entries in this histogram is very bad and typically implies badly timed-in CSCs. To dig out which of the 7 boards is actually responsible for the trouble, one needs to refer the FEB Status (Timeouts, FIFO, L1 pipe) canvas for the offensive chamber (this canvas can be found in the DMB group) For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_DMB_input_timeout_Fract\">here</a>."}])	
	 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 06 - CSCs without Data Blocks",
  	[{'path': "CSC/Summary/CSC_wo_ALCT_Fract", 'description': "Histogram shows how often CSC events come without ALCT data. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_wo_ALCT_Fract\">here</a>."},
	 {'path': "CSC/Summary/CSC_wo_CLCT_Fract", 'description': "Histogram shows how often CSC events come without CLCT data. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_wo_CLCT_Fract\">here</a>."}],
	[{'path': "CSC/Summary/CSC_wo_CFEB_Fract", 'description': "Histogram shows how often CSC events come without CFEB data. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_wo_CFEB_Fract\">here</a>."},
	 {'path': "CSC/Summary/CSC_Format_Warnings_Fract", 'description': "Histogram shows occurrences when SCA cells were filled due to too-high rate of LCTs and/or LCT-L1A coincidences. In conditions of cosmic ray runs, appearance of entries is indicative of hardware problems, or more specifically hot CFEBs. This typically happens due to a loose CFEB-TMB cable generating a flood of CLCT pre-triggers (CBEBs are the only board that are readout on coincidence between pre-CLCT and L1A). For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Format_Warnings_Fract\">here</a>."}])	 
	 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 07 - CSCs Occupancy 2D",
  	[{'path': "CSC/CSCOfflineMonitor/Occupancy/hOStrips", 'description': "Histogram shows strips occupancy per CSC record. CSCs reporting under/over-occupancy should be reported as a cold(dead)/hot-CSC, if it is not mentioned in the white board. For more information on the white bouard please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Format_Errors_Fract\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/Occupancy/hOWires", 'description': "Histogram shows wires occupancy per CSC record. CSCs reporting under/over-occupancy should be reported as a cold(dead)/hot-CSC, if it is not mentioned in the white board. For more information on the white bouard please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Format_Errors_Fract\">here</a>."}],
	 [{'path': "CSC/CSCOfflineMonitor/Occupancy/hORecHits", 'description': "Histogram shows RecHits occupancy per CSC record. CSCs reporting under/over-occupancy should be reported as a cold(dead)/hot-CSC, if it is not mentioned in the white board. For more information on the white bouard please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Format_Errors_Fract\">here</a>."},
	 {'path': "CSC/CSCOfflineMonitor/Occupancy/hOSegments", 'description': "Histogram shows segments occupancy per CSC record. CSCs reporting under/over-occupancy should be reported as a cold(dead)/hot-CSC, if it is not mentioned in the white board. For more information on the white bouard please click <a href=\"https://twiki.cern.ch/twiki/bin/view/CMS/DQMShiftCSC#CSC_Format_Errors_Fract\">here</a>."}]
	 )	 
	 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 08 - CSCs Occupancy Overal",
  	[{'path': "CSC/CSCOfflineMonitor/Occupancy/hCSCOccupancy", 'description': "Histogram shows overal occupancy of CSCs by different types of signals. If there is a substantial difference a problem with overal occupancy should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/Digis/hStripNFired", 'description': "Histogram shows the overal distribution of fired strips per event. If more than 3 peaks are seen a problem with fired strips per event should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."}],
	[{'path': "CSC/CSCOfflineMonitor/Digis/hWirenGroupsTotal", 'description': "Histogram shows the overal distribution of fired wire groups per event. Any unusual  peak should be reported as a problem. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/recHits/hRHnrechits", 'description': "Histogram shows the overal distribution of RecHits per event. If 8 peaks are not seen in a run with good statistics a problem should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."}],
	 ) 
	 	 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 09 - RecHits Minus",
  	[{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalm1", 'description': "Histogram shows 2D RecHits distribution in ME-1. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalm2", 'description': "Histogram shows 2D RecHits distribution in ME-2. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."}],
	[{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalm3", 'description': "Histogram shows 2D RecHits distribution in ME-3. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalm4", 'description': "Histogram shows 2D RecHits distribution in ME-4. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."}
	]
	)
		 		 
csclayout(dqmitems,"00 Data Integrity/Physics Efficiency 10 - RecHits Plus",
  	[{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalp1", 'description': "Histogram shows 2D RecHits distribution in ME+1. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalp2", 'description': "Histogram shows 2D RecHits distribution in ME+2. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."}],
	[{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalp3", 'description': "Histogram shows 2D RecHits distribution in ME+3. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."},
	{'path': "CSC/CSCOfflineMonitor/recHits/hRHGlobalp4", 'description': "Histogram shows 2D RecHits distribution in ME+4. Any unusual inhomogeneity should be reported. For more information please click <a href=\"https://twiki.cern.ch/twiki/bin/viewauth/CMS/CSCDPGDataMonitorShiftInstructions\">here</a>."}
	]
	)