server.service('Online',           'http://cmsmon.cern.ch/dqm/online')
server.service('Online playback',  'http://cmsmon.cern.ch/dqm/online-playback')
server.service('Online test',      'http://cmsmon.cern.ch/dqm/online-test')
server.service('GUI test',         'http://cmsmon.cern.ch/dqm/gui-test')
server.service('CERN Tier-0',      'http://cmsmac01.cern.ch/dqm/tier-0')
server.service('CERN RelVal',      'http://cmsmac01.cern.ch/dqm/relval')
server.service('CERN CAF',         'http://cmsmac01.cern.ch/dqm/caf')
server.service('CERN Development', 'http://cmsmac01.cern.ch/dqm/dev')
