views = [
 ('DT', [
   "Layouts/DT Layouts/DTIntegrityCheck_Summary",
   "Layouts/DT Layouts/W1_St1_Signal",
   "Layouts/DT Layouts/W1_St2_Signal",
   "Layouts/DT Layouts/W1_St3_Signal",
   "Layouts/DT Layouts/W1_St4_Signal",
   "Layouts/DT Layouts/DTLocalTrigger_Station_1",
   "Layouts/DT Layouts/DTLocalTrigger_Station_2",
   "Layouts/DT Layouts/DTLocalTrigger_Station_3",
   "Layouts/DT Layouts/DTLocalTrigger_Station_4",
   "Layouts/DT Layouts/W1_St1_OccupancyPerLayer",
   "Layouts/DT Layouts/W1_St2_OccupancyPerLayer",
   "Layouts/DT Layouts/W1_St3_OccupancyPerLayer",
   "Layouts/DT Layouts/W1_St4_OccupancyPerLayer",
   "Layouts/DT Layouts/DTIntegrityCheck_station1_first",
   "Layouts/DT Layouts/DTIntegrityCheck_station1_second",
   "Layouts/DT Layouts/DTIntegrityCheck_station2_first",
   "Layouts/DT Layouts/DTIntegrityCheck_station2_second",
   "Layouts/DT Layouts/DTIntegrityCheck_station3_first",
   "Layouts/DT Layouts/DTIntegrityCheck_station3_second",
   "Layouts/DT Layouts/DTIntegrityCheck_station4_first",
   "Layouts/DT Layouts/DTIntegrityCheck_station4_second" ]),
 ('ECAL', [
   "Layouts/ECAL Layouts/0-Global-Summary" ]),
 ('EB', [
   "Layouts/EB Layouts/0-Summary/0-Global-Summary",
   "Layouts/EB Layouts/0-Summary/1-Integrity-Summary",
   "Layouts/EB Layouts/0-Summary/2-Occupancy-Summary",
   "Layouts/EB Layouts/0-Summary/3-Cosmic-Summary",
   "Layouts/EB Layouts/0-Summary/4-PedestalOnline-Summary",
   "Layouts/EB Layouts/0-Summary/5-LaserL1-Summary",
   "Layouts/EB Layouts/0-Summary/7-Timing-Summary",
   "Layouts/EB Layouts/0-Summary/8-Trigger-Summary",
   "Layouts/EB Layouts/0-Summary/9-Trigger-Summary" ]),
 ('EE', [
   "Layouts/EE Layouts/0-Summary/0-Global-Summary",
   "Layouts/EE Layouts/0-Summary/1-Integrity-Summary",
   "Layouts/EE Layouts/0-Summary/2-Occupancy-Summary",
   "Layouts/EE Layouts/0-Summary/3-Cosmic-Summary",
   "Layouts/EE Layouts/0-Summary/4-PedestalOnline-Summary",
   "Layouts/EE Layouts/0-Summary/5-LaserL1-Summary",
   "Layouts/EE Layouts/0-Summary/6-Led-Summary",
   "Layouts/EE Layouts/0-Summary/7-Timing-Summary",
   "Layouts/EE Layouts/0-Summary/8-Trigger-Summary",
   "Layouts/EE Layouts/0-Summary/9-Trigger-Summary" ]),
 ('L1T', [
   "Layouts/L1T Layouts/Summary/GT decision bit correlation",
   "Layouts/L1T Layouts/Summary/GT FE Bx",
   "Layouts/L1T Layouts/Summary/GT decision bits",
   "Layouts/L1T Layouts/Summary/DTTF_quality",
   "Layouts/L1T Layouts/Summary/DTTF_eta_value",
   "Layouts/L1T Layouts/Summary/DTTF_phi_value",
   "Layouts/L1T Layouts/Summary/DTTF_ntrack"]),
 ('Strip', [
   "Layouts/Strip Layouts/SiStrip_Digi_Summary"])
]
