def pixellayout(i, p, *rows): i["Pixel/Layouts/" + p] = DQMItem(layout=rows)

pixellayout(dqmitems, "00 - Pixel_RawData_FED_Summary",
  ["Pixel/AdditionalPixelErrors/SUMRAW_NErrors_FEDErrors",
   "Pixel/AdditionalPixelErrors/SUMRAW_errorType_FEDErrors"])
pixellayout(dqmitems, "01 - Pixel_RawData_Barrel_Summary",
  ["Pixel/Barrel/SUMRAW_NErrors_Barrel",
   "Pixel/Barrel/SUMRAW_errorType_Barrel"],
  ["Pixel/Barrel/Shell_mI/SUMRAW_NErrors_Shell_mI",
   "Pixel/Barrel/Shell_mI/SUMRAW_errorType_Shell_mI"],
  ["Pixel/Barrel/Shell_mO/SUMRAW_NErrors_Shell_mO",
   "Pixel/Barrel/Shell_mO/SUMRAW_errorType_Shell_mO"],
  ["Pixel/Barrel/Shell_pI/SUMRAW_NErrors_Shell_pI",
   "Pixel/Barrel/Shell_pI/SUMRAW_errorType_Shell_pI"],
  ["Pixel/Barrel/Shell_pO/SUMRAW_NErrors_Shell_pO",
   "Pixel/Barrel/Shell_pO/SUMRAW_errorType_Shell_pO"])
pixellayout(dqmitems, "02 - Pixel_RawData_Endcap_Summary",
  ["Pixel/Endcap/SUMRAW_NErrors_Endcap",
   "Pixel/Endcap/SUMRAW_errorType_Endcap"],
  ["Pixel/Endcap/HalfCylinder_mI/SUMRAW_NErrors_HalfCylinder_mI",
   "Pixel/Endcap/HalfCylinder_mI/SUMRAW_errorType_HalfCylinder_mI"],
  ["Pixel/Endcap/HalfCylinder_mO/SUMRAW_NErrors_HalfCylinder_mO",
   "Pixel/Endcap/HalfCylinder_mO/SUMRAW_errorType_HalfCylinder_mO"],
  ["Pixel/Endcap/HalfCylinder_pI/SUMRAW_NErrors_HalfCylinder_pI",
   "Pixel/Endcap/HalfCylinder_pI/SUMRAW_errorType_HalfCylinder_pI"],
  ["Pixel/Endcap/HalfCylinder_pO/SUMRAW_NErrors_HalfCylinder_pO",
   "Pixel/Endcap/HalfCylinder_pO/SUMRAW_errorType_HalfCylinder_pO"])
pixellayout(dqmitems, "03 - Pixel_Digi_Occupancy",
  ["Pixel/Endcap/endcapOccupancyMap",
   "Pixel/Barrel/barrelOccupancyMap"])
pixellayout(dqmitems, "04 - Pixel_Digi_Barrel_Summary",
  ["Pixel/Barrel/SUMDIG_adc_Barrel",
   "Pixel/Barrel/SUMDIG_ndigis_Barrel",
   "Pixel/Barrel/SUMDIG_ndigisFREQ_Barrel"],
  ["Pixel/Barrel/Shell_mI/SUMDIG_adc_Shell_mI",
   "Pixel/Barrel/Shell_mI/SUMDIG_ndigis_Shell_mI",
   "Pixel/Barrel/Shell_mI/SUMDIG_ndigisFREQ_Shell_mI"],
  ["Pixel/Barrel/Shell_mO/SUMDIG_adc_Shell_mO",
   "Pixel/Barrel/Shell_mO/SUMDIG_ndigis_Shell_mO",
   "Pixel/Barrel/Shell_mO/SUMDIG_ndigisFREQ_Shell_mO"],
  ["Pixel/Barrel/Shell_pI/SUMDIG_adc_Shell_pI",
   "Pixel/Barrel/Shell_pI/SUMDIG_ndigis_Shell_pI",
   "Pixel/Barrel/Shell_pI/SUMDIG_ndigisFREQ_Shell_pI"],
  ["Pixel/Barrel/Shell_pO/SUMDIG_adc_Shell_pO",
   "Pixel/Barrel/Shell_pO/SUMDIG_ndigis_Shell_pO",
   "Pixel/Barrel/Shell_pO/SUMDIG_ndigisFREQ_Shell_pO"])
pixellayout(dqmitems, "05 - Pixel_Digi_Endcap_Summary",
  ["Pixel/Endcap/SUMDIG_adc_Endcap",
   "Pixel/Endcap/SUMDIG_ndigis_Endcap",
   "Pixel/Endcap/SUMDIG_ndigisFREQ_Endcap"],
  ["Pixel/Endcap/HalfCylinder_mI/SUMDIG_adc_HalfCylinder_mI",
   "Pixel/Endcap/HalfCylinder_mI/SUMDIG_ndigis_HalfCylinder_mI",
   "Pixel/Endcap/HalfCylinder_mI/SUMDIG_ndigisFREQ_HalfCylinder_mI"],
  ["Pixel/Endcap/HalfCylinder_mO/SUMDIG_adc_HalfCylinder_mO",
   "Pixel/Endcap/HalfCylinder_mO/SUMDIG_ndigis_HalfCylinder_mO",
   "Pixel/Endcap/HalfCylinder_mO/SUMDIG_ndigisFREQ_HalfCylinder_mO"],
  ["Pixel/Endcap/HalfCylinder_pI/SUMDIG_adc_HalfCylinder_pI",
   "Pixel/Endcap/HalfCylinder_pI/SUMDIG_ndigis_HalfCylinder_pI",
   "Pixel/Endcap/HalfCylinder_pI/SUMDIG_ndigisFREQ_HalfCylinder_pI"],
  ["Pixel/Endcap/HalfCylinder_pO/SUMDIG_adc_HalfCylinder_pO",
   "Pixel/Endcap/HalfCylinder_pO/SUMDIG_ndigis_HalfCylinder_pO",
   "Pixel/Endcap/HalfCylinder_pO/SUMDIG_ndigisFREQ_HalfCylinder_pO"])
