def pixellayout(i, p, *rows): i["Pixel/Layouts/" + p] = DQMItem(layout=rows)

pixellayout(dqmitems, "00 - Pixel_Error_Summary",
  [{ 'path': "Pixel/AdditionalPixelErrors/SUMRAW_NErrors_FEDErrors",
     'description': "Mean number of errors per FED crate (not associated with a specific module ID - should be empty!", 
     'draw': { 'withref': "no" }}],
  [{ 'path': "Pixel/Barrel/SUMRAW_NErrors_Barrel",
     'description': "Mean number of errors per barrel module - should be empty!",
     'draw': { 'withref': "no" }}],
  [{ 'path': "Pixel/Endcap/SUMRAW_NErrors_Endcap",
     'description': "Mean number of errors per endcap module - should be empty!",
     'draw': { 'withref': "no" }}]
  )
pixellayout(dqmitems, "01 - Pixel_Digi_Occupancy",
  [{ 'path': "Pixel/Endcap/endcapOccupancyMap",
     'description': "Digi occupancy map for all Endcap modules combined",
     'draw': { 'withref': "no" }}],
  [{ 'path': "Pixel/Barrel/barrelOccupancyMap",
     'description': "Digi occupancy map for all Barrel modules combined",
     'draw': { 'withref': "no" }}]
  )
pixellayout(dqmitems, "02 - Pixel_Noise_Summary",
  [{ 'path': "Pixel/Barrel/SUMDIG_ndigisFREQ_Barrel",
     'description': "Total number of events with at least one digi per event per barrel module - spikes show noisy modules or pixels!",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/SUMDIG_ndigisFREQ_Endcap",
     'description': "Total number of events with at least one digi per event per endcap module - spikes show noisy modules or pixels!",
     'draw': { 'withref': "yes" }}]
  )
pixellayout(dqmitems, "03 - Pixel_Charge_Summary",
  [{ 'path': "Pixel/Barrel/ALLMODS_adcCOMB_Barrel",
     'description': "Distribution of raw charge for all digis recorded in the Barrel modules - dominant peak should be around 90-100 ADC",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/ALLMODS_adcCOMB_Endcap",
     'description': "Distribution of raw charge for all digis recorded in the Endcap modules - dominant peak should be around 90-100 ADC",
     'draw': { 'withref': "yes" }}],
  [{ 'path': "Pixel/Barrel/ALLMODS_chargeCOMB_Barrel",
     'description': "Distribution of gain corrected cluster charge for all clusters in the Barrel - dominant peak should be around 21 ke-",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/ALLMODS_chargeCOMB_Endcap",
     'description': "Distribution of gain corrected cluster charge for all clusters in the Endcaps - dominant peak should be around 21 ke-",
     'draw': { 'withref': "yes" }}]
  )     
     
pixellayout(dqmitems, "04 - Pixel_RawData_FED_Summary",
  [{ 'path': "Pixel/AdditionalPixelErrors/SUMRAW_NErrors_FEDErrors",
     'description': "Mean number of errors per FED (not associated with a specific module ID", 
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/AdditionalPixelErrors/SUMRAW_errorType_FEDErrors",
     'description': "Mean of errorType distribution per FED (not associated with a specific module ID",
     'draw': { 'withref': "no" }}])
pixellayout(dqmitems, "05 - Pixel_RawData_Summary",
  [{ 'path': "Pixel/Barrel/SUMRAW_NErrors_Barrel",
     'description': "Mean number of errors per barrel module",
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/Barrel/SUMRAW_errorType_Barrel",
     'description': "Mean of errorType distribution per barrel module",
     'draw': { 'withref': "no" }}],
  [{ 'path': "Pixel/Endcap/SUMRAW_NErrors_Endcap",
     'description': "Mean number of errors per endcap module",
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/Endcap/SUMRAW_errorType_Endcap",
     'description': "Mean of errorType distribution per endcap module",
     'draw': { 'withref': "no" }}])
pixellayout(dqmitems, "06 - Pixel_Digi_Summary",
  [{ 'path': "Pixel/Barrel/SUMDIG_adc_Barrel",
     'description': "Mean digi charge in ADC counts per barrel module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Barrel/SUMDIG_ndigis_Barrel",
     'description': "Mean number of digis per event per barrel module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Barrel/SUMDIG_ndigisFREQ_Barrel",
     'description': "Total number of events with at least one digi per event per barrel module",
     'draw': { 'withref': "yes" }}],
  [{ 'path': "Pixel/Endcap/SUMDIG_adc_Endcap",
     'description': "Mean digi charge in ADC counts per endcap module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/SUMDIG_ndigis_Endcap",
     'description': "Mean number of digis per event per endcap module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/SUMDIG_ndigisFREQ_Endcap",
     'description': "Total number of events with at least one digi per event per endcap module",
     'draw': { 'withref': "yes" }}])
pixellayout(dqmitems, "07 - Pixel_Cluster_Summary",
  [{ 'path': "Pixel/Barrel/SUMCLU_charge_Barrel",
     'description': "Mean cluster charge in kilo electrons per barrel module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Barrel/SUMCLU_nclusters_Barrel",
     'description': "Mean number of clusters per event per barrel module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Barrel/SUMCLU_size_Barrel",
     'description': "Mean cluster size in number of pixels per barrel module",
     'draw': { 'withref': "yes" }}],
  [{ 'path': "Pixel/Endcap/SUMCLU_charge_Endcap",
     'description': "Mean cluster charge in kilo electrons per endcap module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/SUMCLU_nclusters_Endcap",
     'description': "Mean number of clusters per event per endcap module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/SUMCLU_size_Endcap",
     'description': "Mean cluster size in number of pixels per barrel module",
     'draw': { 'withref': "yes" }}])
pixellayout(dqmitems, "08 - Pixel_NoisyPixels_Summary",
  [{ 'path': "Pixel/Barrel/SUMDIG_ndigisFREQ_Barrel",
     'description': "Total number of events with at least one digi per event per barrel module - spikes show noisy modules or pixels!",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/SUMDIG_ndigisFREQ_Endcap",
     'description': "Total number of events with at least one digi per event per endcap module - spikes show noisy modules or pixels!",
     'draw': { 'withref': "yes" }}],
  [{ 'path': "Pixel/Barrel/barrelEventRate",
     'description': "Ratio of events with at least one digi per module over all events taken, one entry per pixel - entries above 0.001 are noisy pixels!",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/endcapEventRate",
     'description': "Ratio of events with at least one digi per module over all events taken, one entry per pixel - entries above 0.001 are noisy pixels!",
     'draw': { 'withref': "yes" }}]
  )

pixellayout(dqmitems, "09 - Barrel_Digi_Occupancy_per_Shell",
  [{ 'path': "Pixel/Barrel/Shell_mI/barrelOccupancyMap",
     'description': "Digi occupancy map for all Barrel Shell_mI modules combined",
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/Barrel/Shell_mO/barrelOccupancyMap",
     'description': "Digi occupancy map for all Barrel Shell_mO modules combined",
     'draw': { 'withref': "no" }}],
  [{ 'path': "Pixel/Barrel/Shell_pI/barrelOccupancyMap",
     'description': "Digi occupancy map for all Barrel Shell_pI modules combined",
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/Barrel/Shell_pO/barrelOccupancyMap",
     'description': "Digi occupancy map for all Barrel Shell_pO modules combined",
     'draw': { 'withref': "no" }}]
  )
pixellayout(dqmitems, "10 - Endcap_Digi_Occupancy_per_HalfCylinder",
  [{ 'path': "Pixel/Endcap/HalfCylinder_mI/endcapOccupancyMap",
     'description': "Digi occupancy map for all Endcap HalfCylinder_mI modules combined",
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/Endcap/HalfCylinder_mO/endcapOccupancyMap",
     'description': "Digi occupancy map for all Endcap HalfCylinder_mO modules combined",
     'draw': { 'withref': "no" }}],
  [{ 'path': "Pixel/Endcap/HalfCylinder_pI/endcapOccupancyMap",
     'description': "Digi occupancy map for all Endcap HalfCylinder_pI modules combined",
     'draw': { 'withref': "no" }},
   { 'path': "Pixel/Endcap/HalfCylinder_pO/endcapOccupancyMap",
     'description': "Digi occupancy map for all Endcap HalfCylinder_pO modules combined",
     'draw': { 'withref': "no" }}]
  )
pixellayout(dqmitems, "11 - Barrel_Digi_Summary_per_Shell",
  [{ 'path': "Pixel/Barrel/Shell_mI/SUMDIG_adc_Shell_mI",
     'description': "Mean digi charge in ADC counts per Barrel Shell_mI module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Barrel/Shell_mO/SUMDIG_ndigis_Shell_mO",
     'description': "Mean number of digis per event per Barrel Shell_mO module",
     'draw': { 'withref': "yes" }}],
  [{ 'path': "Pixel/Barrel/Shell_pI/SUMDIG_adc_Shell_pI",
     'description': "Mean digi charge in ADC counts per Barrel Shell_pI module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Barrel/Shell_pO/SUMDIG_ndigis_Shell_pO",
     'description': "Mean number of digis per event per Barrel Shell_pO module",
     'draw': { 'withref': "yes" }}]
)     
pixellayout(dqmitems, "12 - Endcap_Digi_Summary_per_HalfCylinder",
  [{ 'path': "Pixel/Endcap/HalfCylinder_mI/SUMDIG_adc_HalfCylinder_mI",
     'description': "Mean digi charge in ADC counts per Endcap HalfCylinder_mI module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/HalfCylinder_mO/SUMDIG_ndigis_HalfCylinder_mO",
     'description': "Mean number of digis per event per Endcap HalfCylinder_mO module",
     'draw': { 'withref': "yes" }}],
  [{ 'path': "Pixel/Endcap/HalfCylinder_pI/SUMDIG_adc_HalfCylinder_pI",
     'description': "Mean digi charge in ADC counts per Endcap HalfCylinder_pI module",
     'draw': { 'withref': "yes" }},
   { 'path': "Pixel/Endcap/HalfCylinder_pO/SUMDIG_ndigis_HalfCylinder_pO",
     'description': "Mean number of digis per event per Endcap HalfCylinder_pO module",
     'draw': { 'withref': "yes" }}]
)
