def sistriplayout(i, p, *rows): i["SiStrip/Layouts/" + p] = DQMItem(layout=rows)

sistriplayout(dqmitems, "00 - Tracks",
  [{ 'path': "SiStrip/Tracks/NumberOfTracks_CKFTk",
     'description': ' Number of Reconstructed Tracks by CKF'},
   { 'path': "SiStrip/Tracks/NumberOfRecHitsPerTrack_CKFTk",
     'description': ' Number of RecHits per Track by CKF'}],
  [{ 'path': "SiStrip/Tracks/TrackPhi_CKFTk",
     'description': ' Phi distribution of Reconstructed Tracks by CKF'},
   { 'path': "SiStrip/Tracks/TrackEta_CKFTk",
     'description': ' Eta distribution of Reconstructed Tracks by CKF'}])
sistriplayout(dqmitems, "01 - OnTrackCluster",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_ClusterStoNCorr_OnTrack_in_TIB",
     'description': 'Signal-to-Noise (corrected for the angle) for On-Track clusters in TIB'},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_ClusterStoNCorr_OnTrack_in_TOB",
     'description': 'Signal-to-Noise (corrected for the angle) for On-Track clusters in TOB'}],
  [{ 'path': "SiStrip/MechanicalView/TID/Summary_ClusterStoNCorr_OnTrack_in_TID",
     'description': 'Signal-to-Noise (corrected for the angle) for On-Track clusters in TID'},
  {  'path':"SiStrip/MechanicalView/TEC/Summary_ClusterStoNCorr_OnTrack_in_TEC",
     'description': 'Signal-to-Noise (corrected for the angle) for On-Track clusters in TEC'}])
sistriplayout(dqmitems, "02 - OffTrackCluster",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_ClusterCharge_OffTrack_in_TIB",
     'description': 'Charge for Off-Track clusters in TIB'},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_ClusterCharge_OffTrack_in_TOB",
     'description': 'Charge for Off-Track clusters in TOB'}],
  [{ 'path': "SiStrip/MechanicalView/TID/Summary_ClusterCharge_OffTrack_in_TID",
     'description': 'Charge for Off-Track clusters in TID'},              
   { 'path':"SiStrip/MechanicalView/TEC/Summary_ClusterCharge_OffTrack_in_TEC",
     'description': 'Charge for Off-Track clusters in TEC'}])
sistriplayout(dqmitems, "06 - TOBSummary",
  [{ 'path': "SiStrip/MechanicalView/TOB/Summary_MeanNumberOfDigis__TOB",
     'description': 'Number of Digis from all TOB modules'},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_MeanNumberOfClusters__TOB",
     'description': 'Number of Clusters from all TOB modules'}],
  [{ 'path': "SiStrip/MechanicalView/TOB/Summary_MeanClusterWidth__TOB",
     'description': 'Cluster width from all TOB modules'}, None])
sistriplayout(dqmitems, "03 - TIBSummary",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_MeanNumberOfDigis__TIB",
     'description': 'Number of Digis from all TIB modules'},
   { 'path': "SiStrip/MechanicalView/TIB/Summary_MeanNumberOfClusters__TIB",
     'description': 'Number of Clusters from all TIB modules'}],
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_MeanClusterWidth__TIB",
     'description': 'Cluster width from all TIB modules'}, None])
sistriplayout(dqmitems, "07 - TECFSummary",
  [{ 'path': "SiStrip/MechanicalView/TEC/side_2/Summary_MeanNumberOfDigis__side__2",
     'description': 'Number of Digis from all TECF modules'},
   { 'path': "SiStrip/MechanicalView/TEC/side_2/Summary_MeanNumberOfClusters__side__2",
     'description': 'Number of Clusters from all TECF modules'}],
  [{ 'path': "SiStrip/MechanicalView/TEC/side_2/Summary_MeanClusterWidth__side__2",
     'description': 'Cluster Width from all TECF modules'}, None])
sistriplayout(dqmitems, "08 - TECBSummary",
  [{ 'path': "SiStrip/MechanicalView/TEC/side_1/Summary_MeanNumberOfDigis__side__1",
     'description': 'Number of Digis from all TECB modules'},
   { 'path': "SiStrip/MechanicalView/TEC/side_1/Summary_MeanNumberOfClusters__side__1",
     'description': 'Number of Clusters from all TECB modules'}],
  [{ 'path': "SiStrip/MechanicalView/TEC/side_1/Summary_MeanClusterWidth__side__1",
     'description': 'Cluster width from all TECB modules'}, None])
sistriplayout(dqmitems, "04 - TIDFSummary",
  [{ 'path': "SiStrip/MechanicalView/TID/side_2/Summary_MeanNumberOfDigis__side__2",
     'description': 'Number of Digis from all TIDF modules'},
   { 'path': "SiStrip/MechanicalView/TID/side_2/Summary_MeanNumberOfClusters__side__2",
     'description': 'Number of Clusters from all TIDF modules'}],     
  [{ 'path': "SiStrip/MechanicalView/TID/side_2/Summary_MeanClusterWidth__side__2",
     'description': 'Cluster width from all TIDF modules'}, None]) 
sistriplayout(dqmitems, "05 - TIDBSummary",
  [{ 'path': "SiStrip/MechanicalView/TID/side_1/Summary_MeanNumberOfDigis__side__1",
     'description': 'Number of Digis from all TIDB modules'},
   { 'path': "SiStrip/MechanicalView/TID/side_1/Summary_MeanNumberOfClusters__side__1",
     'description': 'Number of Clusters from all TIDB modules'}],     
  [{ 'path': "SiStrip/MechanicalView/TID/side_1/Summary_MeanClusterWidth__side__1",
     'description': 'Cluster width from all TIDB modules'}, None])
sistriplayout(dqmitems, "09 - FedMonitoringSummary",
  [{ 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FaultyChannelsVsEvent",
     'description': 'Total number of faulty channels per event (first 1000 events are used)'},
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedBxError",
     'description': 'Total number of FEDs with BxError'},      
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedFreeze",
     'description': 'Total number of FEDs with FedFreeze error'}],   
  [{ 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedGenericErrors",
     'description': 'Total numbers of errors per FED'},
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/TotalChannelsVsEvent",
     'description': 'Total number of active channels per event (first 1000 events are used)'},
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedCorruptBuffer",
     'description': '# of Corrupted Buffers vs FED ID'}])
