def sistriplayout(i, p, *rows): i["SiStrip/Layouts/" + p] = DQMItem(layout=rows)

sistriplayout(dqmitems, "00 - Tracks",
  [{ 'path': "SiStrip/Tracks/NumberOfTracks_CKFTk",
     'description': ' Number of Reconstructed Tracks by CKF'},
   { 'path': "SiStrip/Tracks/NumberOfRecHitsPerTrack_CKFTk",
     'description': ' Number of RecHits per Track by CKF'}],
  [{ 'path': "SiStrip/Tracks/TrackPhi_CKFTk",
     'description': ' Phi distribution of Reconstructed Tracks by CKF'},
   { 'path': "SiStrip/Tracks/TrackEta_CKFTk",
     'description': ' Eta distribution of Reconstructed Tracks by CKF'}])
sistriplayout(dqmitems, "01 - OnTrackCluster",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_cStoN_OnTrack_in_TIB",
     'description': 'Signal-to-Noise from On-Track clusters in TIB'},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_cStoN_OnTrack_in_TOB",
     'description': 'Signal-to-Noise from On-Track clusters in TOB'}],
  [{ 'path':"SiStrip/MechanicalView/TEC/Summary_cStoN_OnTrack_in_TEC",
     'description': 'Signal-to-Noise from On-Track clusters in TEC'},
   { 'path': "SiStrip/MechanicalView/TID/Summary_cStoN_OnTrack_in_TID",
     'description': 'Signal-to-Noise from On-Track clusters in TID'}])
sistriplayout(dqmitems, "02 - OffTrackCluster",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_cStoN_OffTrack_in_TIB",
     'description': 'Signal-to-Noise from Off-Track clusters in TIB'},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_cStoN_OffTrack_in_TOB",
     'description': 'Signal-to-Noise from Off-Track clusters in TOB'}],
  [{ 'path':"SiStrip/MechanicalView/TEC/Summary_cStoN_OffTrack_in_TEC",
     'description': 'Signal-to-Noise from Off-Track clusters in TEC'},
   { 'path': "SiStrip/MechanicalView/TID/Summary_cStoN_OffTrack_in_TID",
     'description': 'Signal-to-Noise from Off-Track clusters in TID'}])
sistriplayout(dqmitems, "06 - TOBSummary",
  [{ 'path': "SiStrip/MechanicalView/TOB/Summary_NumberOfDigis_in_TOB",
     'description': 'Number of Digis from all TOB modules'},
   { 'path': "SiStrip/MechanicalView/TOB/Summary_NumberOfClusters_in_TOB",
     'description': 'Number of Clusters from all TOB modules'}],
  [{ 'path': "SiStrip/MechanicalView/TOB/Summary_ClusterWidth_in_TOB",
     'description': 'Cluster width from all TOB modules'}, None])
sistriplayout(dqmitems, "03 - TIBSummary",
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_NumberOfDigis_in_TIB",
     'description': 'Number of Digis from all TIB modules'},
   { 'path': "SiStrip/MechanicalView/TIB/Summary_NumberOfClusters_in_TIB",
     'description': 'Number of Clusters from all TIB modules'}],
  [{ 'path': "SiStrip/MechanicalView/TIB/Summary_ClusterWidth_in_TIB",
     'description': 'Cluster width from all TIB modules'}, None])
sistriplayout(dqmitems, "07 - TECFSummary",
  [{ 'path': "SiStrip/MechanicalView/TEC/side_2/Summary_NumberOfDigis_in_side_2",
     'description': 'Number of Digis from all TECF modules'},
   { 'path': "SiStrip/MechanicalView/TEC/side_2/Summary_NumberOfClusters_in_side_2",
     'description': 'Number of Clusters from all TECF modules'}],
  [{ 'path': "SiStrip/MechanicalView/TEC/side_2/Summary_ClusterWidth_in_side_2",
     'description': 'Cluster Width from all TECF modules'}, None])
sistriplayout(dqmitems, "08 - TECBSummary",
  [{ 'path': "SiStrip/MechanicalView/TEC/side_1/Summary_NumberOfDigis_in_side_1",
     'description': 'Number of Digis from all TECB modules'},
   { 'path': "SiStrip/MechanicalView/TEC/side_1/Summary_NumberOfClusters_in_side_1",
     'description': 'Number of Clusters from all TECB modules'}],
  [{ 'path': "SiStrip/MechanicalView/TEC/side_1/Summary_ClusterWidth_in_side_1",
     'description': 'Cluster width from all TECB modules'}, None])
sistriplayout(dqmitems, "04 - TIDFSummary",
  [{ 'path': "SiStrip/MechanicalView/TID/side_2/Summary_NumberOfDigis_in_side_2",
     'description': 'Number of Digis from all TIDF modules'},
   { 'path': "SiStrip/MechanicalView/TID/side_2/Summary_NumberOfClusters_in_side_2",
     'description': 'Number of Clusters from all TIDF modules'}],     
  [{ 'path': "SiStrip/MechanicalView/TID/side_2/Summary_ClusterWidth_in_side_2",
     'description': 'Cluster width from all TIDF modules'}, None]) 
sistriplayout(dqmitems, "05 - TIDBSummary",
  [{ 'path': "SiStrip/MechanicalView/TID/side_1/Summary_NumberOfDigis_in_side_1",
     'description': 'Number of Digis from all TIDB modules'},
   { 'path': "SiStrip/MechanicalView/TID/side_1/Summary_NumberOfClusters_in_side_1",
     'description': 'Number of Clusters from all TIDB modules'}],     
  [{ 'path': "SiStrip/MechanicalView/TID/side_1/Summary_ClusterWidth_in_side_1",
     'description': 'Cluster width from all TIDB modules'}, None])
sistriplayout(dqmitems, "09 - FedMonitoringSummary",
  [{ 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FaultyChannelsVsEvent",
     'description': 'Total number of faulty channels per event (first 1000 events are used)'},
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedBxError",
     'description': 'Total number of FEDs with BxError'},      
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedFreeze",
     'description': 'Total number of FEDs with FedFreeze error'}],   
   [{ 'path': "SiStrip/ReadoutView/FedMonitoringSummary/FedGenericErrors",
     'description': 'Total numbers of errors per FED'},
   { 'path': "SiStrip/ReadoutView/FedMonitoringSummary/TotalChannelsVsEvent",
     'description': 'Total number of active channels per event (first 1000 events are used)'}, None])
