#!/bin/zsh
DQM_V=5.1.1
DQM_SW=/data/sw
. $DQM_SW/cmsset_default.sh
. $DQM_SW/slc4_ia32_gcc345/cms/dqmgui/$DQM_V/etc/profile.d/env.sh
NOW=$(date +%Y%m%d%H%M%S)

for D in offline caf dev; do
  DQM_BASE=/data/dqm/$D
  mkdir -p $DQM_BASE/agents
  cd $DQM_BASE
  (visDQMReceiveDaemon $DQM_BASE/{uploads,repository/data,agents/register,agents/zip}) >& $DQM_BASE/agents/receive-$NOW.log </dev/null &
  (visDQMZipDaemon $DQM_BASE/{agents/zip,repository/data,repository/zipped,agents/stageout}) >& $DQM_BASE/agents/zip-$NOW.log </dev/null &
  (visDQMImportDaemon $DQM_BASE/{agents/register,repository/data,ix,agents/historic}) >& $DQM_BASE/agents/import-$NOW.log </dev/null &
done
