#!/bin/zsh
DQM_V=5.1.1
DQM_SW=/data/sw
. $DQM_SW/cmsset_default.sh
. $DQM_SW/slc4_ia32_gcc345/cms/dqmgui/$DQM_V/etc/profile.d/env.sh
NOW=$(date +%Y%m%d%H%M%S)

for D in offline caf dev; do
  DQM_BASE=/data/dqm/$D
  mkdir -p $DQM_BASE/agents
  cd $DQM_BASE
  (for f in $(find $DQM_BASE/old/data -name '*.root.origin' | sort); do
     if [ $(find $DQM_BASE/repository/data -name $(basename ${f%.origin}) | wc -l) = 0 ]; then
       v=$(basename $f | sed 's/.*_V\([0-9][0-9][0-9][0-9]\)_.*/\1/')
       b=$DQM_BASE/uploads/$v/$(basename $f | sed s/_V${v}_/_V0001_/)
       if [ ! -f $b -a ! -f $b.bad ]; then
         mkdir -p $(dirname $b)
         ln $f $b
         ln ${f%.origin} ${b%.origin}
       fi
     fi
   done) >>& $DQM_BASE/agents/upload-$NOW.log </dev/null &
done
