#!/bin/zsh
DQM_V=5.1.4
DQM_BASE=/home/dqm
DQM_DATA=/dqmdata/dqm
DQM_SW=$DQM_BASE/rpms
. $DQM_SW/cmsset_default.sh
. $DQM_SW/slc4_ia32_gcc345/cms/dqmgui/$DQM_V/etc/profile.d/env.sh
NOW=$(date +%Y%m%d%H%M%S)

mkdir -p $DQM_DATA/repository/original \
         $DQM_DATA/repository/merged \
         $DQM_DATA/agents \
         $DQM_BASE/agents

(visDQMReceiveDaemon \
  $DQM_DATA/uploads \
  $DQM_DATA/repository/original \
  $DQM_DATA/agents/register \
  $DQM_DATA/agents/merge \
) >& $DQM_BASE/agents/receive-$NOW.log </dev/null &

(visDQMImportDaemon \
  $DQM_DATA/agents/register \
  $DQM_DATA/repository/original \
  $DQM_BASE/ix \
) >& $DQM_BASE/agents/import-$NOW.log </dev/null &

(visDQMMergeDaemon \
  $DQM_DATA/agents/merge \
  $DQM_DATA/repository/original \
  $DQM_DATA/repository/merged \
  $DQM_DATA/agents/t0xfer
) >& $DQM_BASE/agents/merge-$NOW.log </dev/null &
