#!/usr/bin/env python
import os, datetime, time,  sys, shutil, glob, re, subprocess as sp,tempfile
from commonAnTS import *
if len(sys.argv)<=1 or not os.path.exists(sys.argv[1]):
  print "No valid configuration file"
  sys.exit()
execfile(sys.argv[1])
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
#####         MAIN PROGRAM         ######
if not os.path.exists(REPOSITORY_DIR):
  DEBUG and debugMsg(0,"Creating directory '%s'" % REPOSITORY_DIR)
  os.makedirs(REPOSITORY_DIR)
  
if not os.path.exists(DROPBOX):
  DEBUG and debugMsg(0,"Creating directory '%s'" % DROPBOX)
  os.makedirs(DROPBOX)
  
if not os.path.exists(TMP_DROPBOX):
  DEBUG and debugMsg(0,"Creating directory '%s'" % TMP_DROPBOX)
  os.makedirs(TMP_DROPBOX)
  
while True:
  #get list of directories from castor
  cmd="rfdir %s/%s | awk '{print($9)}'" % (CASTOR_BASE,INSTANCE_DIR)
  DEBUG and debugMsg(0,"Calling shell command '%s'" % cmd)
  (cmdHdl,error,retcode)=executeCmd(cmd)
  if retcode == None or retcode > 0:
    debugMsg(2,"Command '%s' returned with code %s and error message: %s " % (cmd,str(retcode) or "None" ,error.read().replace("\n","@")))
    continue 
  dirlist=cmdHdl.read().split()
  if not dirlist:
    DEBUG and debugMsg(1,"No directories found, retrying in '%d' seconds" % CASTOR_WAIT_TIME)
    time.sleep(CASTOR_WAIT_TIME)
    continue
  WATCH_DIR=[]  
  #select the directories that are going to be watched
  for directory in dirlist:
    repoFile="%s/%s.rep" % (REPOSITORY_DIR,directory)
    if not os.path.exists(repoFile):
      WATCH_DIR.append(directory)
      DEBUG and debugMsg(0,"Directory %s/%s/%s added to watch list" % (CASTOR_BASE,INSTANCE_DIR,directory))
    else:
      repoyear=int(directory[:4])
      repomonth=int(directory[4:])
      if datetime.date.today().year == repoyear and repomonth+1 >= datetime.date.today().month:
        WATCH_DIR.append(directory)
        DEBUG and debugMsg(0,"Directory %s/%s/%s added to watch list")
  #Find what files have been processed
  PROCESSED_FILES_LIST=[]
  for directory in WATCH_DIR:
    repoFile="%s/%s.rep" % (REPOSITORY_DIR,directory)
    if not os.path.exists(repoFile):
      debugMsg(0,"Repository File %s does not exists, found new directory!" % repoFile)
      continue
    f=open(repoFile,"r")
    foundFiles=[x.strip() for x in f.readlines()]
    DEBUG and debugMsg(0,"Found %d processed files in %s" % (len(foundFiles),directory))
    if len(foundFiles): 
      PROCESSED_FILES_LIST.extend(foundFiles)
    f.close()
  debugMsg(0,"Found %d files already processed" % len(PROCESSED_FILES_LIST))
  #Create list of files to copy
  NEW_FILES_DICT={}
  newFilesFound=0
  for directory in WATCH_DIR:  
    repoFile="%s/%s.rep" % (REPOSITORY_DIR,directory)
    cmd="rfdir %s/%s/%s | grep \"%s\" | awk '{print($5\" \"$9)}'" % (CASTOR_BASE,INSTANCE_DIR,directory,FILE_TYPE)
    DEBUG and debugMsg(0,"Calling shell command '%s'" % cmd)
    (cmdHdl,error,retcode)=executeCmd(cmd)
    if retcode == None or retcode > 0:
      debugMsg(2,"Command '%s' returned with code %s and error message: %s " % (cmd,str(retcode) or "None" ,error.read().replace("\n","@")))
      continue 
    fileList=cmdHdl.read().split("\n")
    for newFile in fileList:
      if newFile:
        newFileName=newFile.split()[1]
        newFileSize=newFile.split()[0]
        if newFileName not in sorted(PROCESSED_FILES_LIST) :
          newFilesFound=newFilesFound+1
          fileName="%s/%s/%s/%s" % (CASTOR_BASE,INSTANCE_DIR,directory,newFileName)
          NEW_FILES_DICT.setdefault(fileName,[long(newFileSize),repoFile])
  debugMsg(0,"Found %d new files to copy" % newFilesFound)
  #Copy Files
  for newFile, info in NEW_FILES_DICT.items():
    cmd="rfcp %s %s" % (newFile,TMP_DROPBOX)
    DEBUG and debugMsg(0,"Calling shell command '%s'" % cmd)
    (cmdHdl,error,retcode)=executeCmd(cmd)
    if retcode == None or retcode > 0:
      debugMsg(2,"Command '%s' returned with code %s and error message: %s " % (cmd,str(retcode) or "None" ,error.read().replace("\n","@")))
      continue 
    cmdOutput=cmdHdl.read().replace("\n","@")
    DEBUG and debugMsg(0,"Command output: '%s'" % cmdOutput)
    newFileTemp="%s/%s" % (TMP_DROPBOX,os.path.basename(newFile))
    newFileDest="%s/%s" % (DROPBOX,os.path.basename(newFile))
    repoFile=open(info[1],"a")
    if os.path.exists(newFileTemp) and os.stat(newFileTemp).st_size == info[0]:
      os.rename(newFileTemp,newFileDest)
      debugMsg(0,"File '%s' was succesfully tranferred" % newFile)
      repoFile.write("%s\n" % os.path.basename(newFileDest))
      DEBUG and debugMsg(0,"Calling shell command '%s'" % cmd)
    else:
      debugMsg(3,"File '%s' failed to tranfer" % newFile)
      if os.path.exists(newFileTemp):
        debugMsg(2,"File '%s' was not tranfered completly, expected %d bytes and got %d bytes, removing tmp file" % (newFile,info[0],os.stat(newFileTemp).st_size))
        os.remove(newFileTemp)
      else:
        debugMsg(2,"rfcp failed wi error message: %s" % cmdOutput)
    repoFile.close()
  DEBUG and debugMsg(0,"Finished processing list going to sleep for: '%d' seconds" % CASTOR_WAIT_TIME)
  time.sleep(CASTOR_WAIT_TIME)
